name: CI/CD Pipeline for E-commerce App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy mã nguồn từ GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build và Push Docker image cho Backend
      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend:latest

      # 4. Build và Push Docker image cho Frontend
      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-frontend:latest
